runtime: go121
app_engine_apis: true

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  static_files: static/home.html
  upload: static/home.html

- url: /.*
  script: auto
